feat: add skipSeleniumInstall config option
webdriverio-boneyard/wdio-selenium-standalone-service pull request #55
Opened 2018-12-09 12:04 UTC by dotEightyOne

let's start all over :)

2018-12-09 13:41 UTC, christian-bromann requested changes
Two comments, also please apply the same fix for the v5 repo: https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-selenium-standalone-service

2018-12-09 13:41 UTC, christian-bromann commented on README.md
> +```
I don't think this config needs an example as it is a simple boolean property.

2018-12-09 13:41 UTC, christian-bromann commented on lib/launcher.js
> +        return this._installSeleniumDependencies(this.seleniumInstallArgs).then(() => launcher._startSelenium(launcher.seleniumArgs))
let's use [`util.promisify`](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_promisify_original) instead of `_startSelenium`

2018-12-09 22:59 UTC, christian-bromann approved these changes
Change looks good. Can merge once a similar PR is made to v5

2018-12-11 08:51 UTC, dotEightyOne commented
PR on v5 is open.

2018-12-11 10:26 UTC, merged

2018-12-11 10:28 UTC, christian-bromann commented
Released as `v0.0.12`